name: alrahma
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.9.1
  flutter_dotenv: ^5.2.1
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  get_it: ^8.2.0
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  flutter_bloc: ^9.1.1
  flutter_screenutil: ^5.9.3
  bidi: ^2.0.13
  file_saver: ^0.3.1
  flutter_launcher_icons: ^0.14.4
  device_info_plus: ^11.5.0
  sqflite: ^2.4.2
  crypto: ^3.0.6
  fl_chart: ^0.68.0
  path: ^1.9.1
  connectivity_plus: ^7.0.0
  pdf: ^3.11.3
  printing: ^5.14.2
  gal: ^2.3.2
  image_picker: ^1.2.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: 2.4.14
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/images/

fonts:
  - family: Cairo
    fonts:
      - asset: assets/fonts/Cairo-Regular.ttf
        weight: 400
  - family: Cairo
    fonts:
      - asset: assets/fonts/Cairo-Medium.ttf
        weight: 500
      - asset: assets/fonts/Cairo-Bold.ttf
        weight: 700

      
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/alRaham_logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/alRaham_logo.png"
